// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// lambshade_cpp
NumericMatrix lambshade_cpp(NumericMatrix heightmap, NumericVector rayvector);
RcppExport SEXP _rPET_lambshade_cpp(SEXP heightmapSEXP, SEXP rayvectorSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type heightmap(heightmapSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type rayvector(rayvectorSEXP);
    rcpp_result_gen = Rcpp::wrap(lambshade_cpp(heightmap, rayvector));
    return rcpp_result_gen;
END_RCPP
}
// rayshade_cpp
NumericMatrix rayshade_cpp(double sunangle, NumericVector anglebreaks, NumericMatrix& heightmap, NumericMatrix& addressmap, NumericMatrix& lengthmap, NumericMatrix& pointcloud, double zscale, double maxsearch, double maxheight, const NumericMatrix cache_mask, bool progbar);
RcppExport SEXP _rPET_rayshade_cpp(SEXP sunangleSEXP, SEXP anglebreaksSEXP, SEXP heightmapSEXP, SEXP addressmapSEXP, SEXP lengthmapSEXP, SEXP pointcloudSEXP, SEXP zscaleSEXP, SEXP maxsearchSEXP, SEXP maxheightSEXP, SEXP cache_maskSEXP, SEXP progbarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type sunangle(sunangleSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type anglebreaks(anglebreaksSEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type heightmap(heightmapSEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type addressmap(addressmapSEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type lengthmap(lengthmapSEXP);
    Rcpp::traits::input_parameter< NumericMatrix& >::type pointcloud(pointcloudSEXP);
    Rcpp::traits::input_parameter< double >::type zscale(zscaleSEXP);
    Rcpp::traits::input_parameter< double >::type maxsearch(maxsearchSEXP);
    Rcpp::traits::input_parameter< double >::type maxheight(maxheightSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix >::type cache_mask(cache_maskSEXP);
    Rcpp::traits::input_parameter< bool >::type progbar(progbarSEXP);
    rcpp_result_gen = Rcpp::wrap(rayshade_cpp(sunangle, anglebreaks, heightmap, addressmap, lengthmap, pointcloud, zscale, maxsearch, maxheight, cache_mask, progbar));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_rPET_lambshade_cpp", (DL_FUNC) &_rPET_lambshade_cpp, 2},
    {"_rPET_rayshade_cpp", (DL_FUNC) &_rPET_rayshade_cpp, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_rPET(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
