# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

lambshade_cpp <- function(heightmap, rayvector) {
    .Call(`_rPET_lambshade_cpp`, heightmap, rayvector)
}

rayshade_cpp <- function(sunangle, anglebreaks, heightmap, addressmap, lengthmap, pointcloud, zscale, maxsearch, maxheight, cache_mask, progbar) {
    .Call(`_rPET_rayshade_cpp`, sunangle, anglebreaks, heightmap, addressmap, lengthmap, pointcloud, zscale, maxsearch, maxheight, cache_mask, progbar)
}

